### ISSUE TITLE
Opencomputers callback error with deep resonence

### ISSUE THREAD

**Issue by weeryan17** [McJty/DeepResonance#107]
If you have opencomputers installed and use it to test purity, efficiency, or strength and the tank your testing is empty it has a null pointer exception and throws a lua callback error
here is the error log:
[12:33:12] [Server thread/WARN] [OpenComputers]: Unexpected error in Lua callback.
java.lang.NullPointerException
	at mcjty.deepresonance.integration.computers.TankDriver$OCDriver$InternalManagedEnvironment.getStrength(TankDriver.java:54) ~[TankDriver$OCDriver$InternalManagedEnvironment.class:?]
	at generated.li.cil.oc.CallWrapper_mcjty_deepresonance_integration_computers_TankDriver$OCDriver$InternalManagedEnvironment_getStrength.call(Unknown Source) ~[?:?]
	at li.cil.oc.server.machine.Callbacks$ComponentCallback.apply(Callbacks.scala:123) ~[Callbacks$ComponentCallback.class:?]
	at li.cil.oc.server.network.Component$class.invoke(Component.scala:112) ~[Component$class.class:?]
	at li.cil.oc.server.network.Network$ComponentBuilder$$anon$2.invoke(Network.scala:600) ~[Network$ComponentBuilder$$anon$2.class:?]
	at li.cil.oc.server.machine.Machine.invoke(Machine.scala:356) ~[Machine.class:?]
	at li.cil.oc.server.machine.luac.ComponentAPI$$anonfun$initialize$5$$anonfun$apply$6.apply(ComponentAPI.scala:78) ~[ComponentAPI$$anonfun$initialize$5$$anonfun$apply$6.class:?]
	at li.cil.oc.server.machine.luac.ComponentAPI$$anonfun$initialize$5$$anonfun$apply$6.apply(ComponentAPI.scala:78) ~[ComponentAPI$$anonfun$initialize$5$$anonfun$apply$6.class:?]
	at li.cil.oc.server.machine.luac.NativeLuaArchitecture.invoke(NativeLuaArchitecture.scala:55) [NativeLuaArchitecture.class:?]
	at li.cil.oc.server.machine.luac.ComponentAPI$$anonfun$initialize$5.apply(ComponentAPI.scala:78) [ComponentAPI$$anonfun$initialize$5.class:?]
	at li.cil.oc.server.machine.luac.ComponentAPI$$anonfun$initialize$5.apply(ComponentAPI.scala:74) [ComponentAPI$$anonfun$initialize$5.class:?]
	at li.cil.oc.util.ExtendedLuaState$ExtendedLuaState$$anon$1.invoke(ExtendedLuaState.scala:24) [ExtendedLuaState$ExtendedLuaState$$anon$1.class:?]
	at li.cil.repack.com.naef.jnlua.LuaState.lua_pcall(Native Method) [LuaState.class:?]
	at li.cil.repack.com.naef.jnlua.LuaState.call(LuaState.java:677) [LuaState.class:?]
	at li.cil.oc.server.machine.luac.NativeLuaArchitecture.runSynchronized(NativeLuaArchitecture.scala:177) [NativeLuaArchitecture.class:?]
	at li.cil.oc.server.machine.Machine.update(Machine.scala:560) [Machine.class:?]
	at li.cil.oc.server.component.Server.update(Server.scala:203) [Server.class:?]
	at li.cil.oc.common.inventory.ComponentInventory$class.updateComponents(ComponentInventory.scala:38) [ComponentInventory$class.class:?]
	at li.cil.oc.common.tileentity.Rack.updateComponents(Rack.scala:32) [Rack.class:?]
	at li.cil.oc.common.tileentity.Rack.updateEntity(Rack.scala:369) [Rack.class:?]
	at li.cil.oc.common.tileentity.traits.Tickable$class.update(Tickable.scala:6) [Tickable$class.class:?]
	at li.cil.oc.common.tileentity.Rack.func_73660_a(Rack.scala:32) [Rack.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1802) [aid.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618) [ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]

**Comment by McJty** [comment]
Fixed next release
