### ISSUE TITLE
Server crash - Ticking block entity

### ISSUE THREAD

**Issue by ProsperCraft** [McJty/DeepResonance#151]
deepresonance{1.3.1}
Forge 12.18.2.2171

Large multiplayer server, what the players were doing? no idea.

https://gist.github.com/ProsperCraft/e997205ac41c0119eacc8559387480b6

Description: Ticking block entity

java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=working, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:196)
	at mcjty.deepresonance.blocks.smelter.SmelterTileEntity.checkStateServer(SmelterTileEntity.java:83)
	at mcjty.deepresonance.blocks.smelter.SmelterTileEntity.func_73660_a(SmelterTileEntity.java:67)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:211)
	at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zjl000(WorldServer.java:1298)
	at net.minecraft.world.World.func_72939_s(World.java:1282)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:713)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

**Comment by ProsperCraft** [comment]
https://github.com/McJty/DeepResonance/issues/91
