### ISSUE TITLE
FluidTankWrapper is still crashing with a NPE

### ISSUE THREAD

**Issue by joserobjr** [McJty/DeepResonance#166]
This other issue https://github.com/McJty/DeepResonance/issues/121 is marked as resolved but the crash is still happening.

The NPE is happening frequently but not all the time, I can teleport to the block and see it there, but it eventually crashes after I leave.

I think this happens when the chunk unloads.

Full crash report: http://pastebin.com/Q4Dab30Q

Block being ticked:
![2017-01-12_14 54 24](https://cloud.githubusercontent.com/assets/3679022/21901592/216a2c32-d8d7-11e6-8caf-eb42698557c8.png)
![2017-01-12_14 54 38](https://cloud.githubusercontent.com/assets/3679022/21901595/245b575e-d8d7-11e6-8d09-5810613adb2b.png)

```java
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at mcjty.deepresonance.varia.FluidTankWrapper.drain(FluidTankWrapper.java:62)
	at com.enderio.core.common.fluid.CapabilityFluidWrapper.getAvailableFluid(CapabilityFluidWrapper.java:41)
	at crazypants.enderio.conduit.liquid.EnderLiquidConduitNetwork.extractFrom(EnderLiquidConduitNetwork.java:50)
	at crazypants.enderio.conduit.liquid.EnderLiquidConduit.doExtract(EnderLiquidConduit.java:257)
	at crazypants.enderio.conduit.liquid.EnderLiquidConduit.updateEntity(EnderLiquidConduit.java:237)
	at crazypants.enderio.conduit.TileConduitBundle.doUpdate(TileConduitBundle.java:239)
	at com.enderio.core.common.TileEntityBase.func_73660_a(TileEntityBase.java:36)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:214)
	at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:1345)
	at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zjl000(WorldServer.java:1332)
	at net.minecraft.world.World.func_72939_s(World.java:1282)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:726)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

-- Block entity being ticked --
Details:
	Name: blockConduitBundleTileEntity // crazypants.enderio.conduit.TileConduitBundle
	Block type: ID #941 (tile.blockConduitBundle // crazypants.enderio.conduit.BlockConduitBundle)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (740,82,362), Chunk: (at 4,5,10 in 46,22; contains blocks 736,0,352 to 751,255,367), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Actual block type: ID #941 (tile.blockConduitBundle // crazypants.enderio.conduit.BlockConduitBundle)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1282)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:726)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Linux (amd64) version 2.6.32-642.4.2.el6.x86_64
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2295153640 bytes (2188 MB) / 4292345856 bytes (4093 MB) up to 7473725440 bytes (7127 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2202 90 mods loaded, 90 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2202-universal.jar) 
	UCHIJAAAA	Forge{12.18.3.2202} [Minecraft Forge] (forge-1.10.2-12.18.3.2202-universal.jar) 
	UCHIJAAAA	Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.9.4-1.1.1.1.jar) 
	UCHIJAAAA	OpenComputers|Core{1.6.0.4} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAAAA	spongeapi{5.1.0-SNAPSHOT-428c0b2} [SpongeAPI] (minecraft.jar) 
	UCHIJAAAA	sponge{1.10.2-2202-5.1.0-BETA-5} [SpongeForge] (spongeforge-1.10.2-2202-5.1.0-BETA-5.jar) 
	UCHIJAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.4.3.165-universal.jar) 
	UCHIJAAAA	minecity{1.0.A.4-SNAPSHOT} [MineCity] (MineCity-Sponge-1.0.A.4-SNAPSHOT.jar) 
	UCHIJAAAA	minecitysponge{} [MineCity-Sponge] (MineCity-Sponge-1.0.A.4-SNAPSHOT.jar) 
	UCHIJAAAA	actuallyadditions{1.10.2-r97} [Actually Additions] (ActuallyAdditions-1.10.2-r97.jar) 
	UCHIJAAAA	JEI{3.13.5.385} [Just Enough Items] (jei_1.10.2-3.13.5.385.jar) 
	UCHIJAAAA	appleskin{1.0.4} [AppleSkin] (AppleSkin-mc1.10.2-1.0.4.jar) 
	UCHIJAAAA	Aroma1997CoreHelper{1.1.1.1} [Aroma1997Core|Helper] (Aroma1997Core-1.9.4-1.1.1.1.jar) 
	UCHIJAAAA	Aroma1997sDimension{1.0} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.9.4-1.2.0.3.jar) 
	UCHIJAAAA	Quark{r1.1-70} [Quark] (Quark-r1.1-70.jar) 
	UCHIJAAAA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJAAAA	bdlib{1.12.2.17} [BD Lib] (bdlib-1.12.2.17-mc1.10.2.jar) 
	UCHIJAAAA	BiomesOPlenty{5.0.0.2109} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2109-universal.jar) 
	UCHIJAAAA	bookshelf{1.4.3.338} [Bookshelf] (Bookshelf-1.10.2-1.4.3.338.jar) 
	UCHIJAAAA	Chameleon{1.10-2.1.9} [Chameleon] (Chameleon-1.10-2.1.9.jar) 
	UCHIJAAAA	mcmultipart{1.3.0} [MCMultiPart] (MCMultiPart-1.3.0-universal.jar) 
	UCHIJAAAA	CharsetLib{0.3.4} [‽] (Charset-mc1.10.2-0.3.4-9bf078fd9a3d0d9a.jar) 
	UCHIJAAAA	CharsetPipes{0.3.4} [|] (Charset-mc1.10.2-0.3.4-9bf078fd9a3d0d9a.jar) 
	UCHIJAAAA	CharsetTweaks{0.3.4} [*] (Charset-mc1.10.2-0.3.4-9bf078fd9a3d0d9a.jar) 
	UCHIJAAAA	CharsetAudio{0.3.4} [♫] (Charset-mc1.10.2-0.3.4-9bf078fd9a3d0d9a.jar) 
	UCHIJAAAA	CharsetStorage{0.3.4} [#] (Charset-mc1.10.2-0.3.4-9bf078fd9a3d0d9a.jar) 
	UCHIJAAAA	CharsetDecoration{0.3.4} [^] (Charset-mc1.10.2-0.3.4-9bf078fd9a3d0d9a.jar) 
	UCHIJAAAA	CharsetWrench{0.3.4} [/] (Charset-mc1.10.2-0.3.4-9bf078fd9a3d0d9a.jar) 
	UCHIJAAAA	chisel{MC1.10.2-0.0.7.3} [Chisel] (Chisel-MC1.10.2-0.0.7.3.jar) 
	UCHIJAAAA	chiselsandbits{12.7} [Chisels & Bits] (chiselsandbits-12.7.jar) 
	UCHIJAAAA	CodeChickenLib{2.4.3.165} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.4.3.165-universal.jar) 
	UCHIJAAAA	cookingforblockheads{4.2.26} [Cooking for Blockheads] (CookingForBlockheads_1.10.2-4.2.26.jar) 
	UCHIJAAAA	covers{0.4.1.13} [Simple Covers] (covers-0.4.1.13-mc1.10.2.jar) 
	UCHIJAAAA	darkutils{1.1.6.99} [Dark Utilities] (DarkUtilities-1.10.2-1.1.6.99.jar) 
	UCHIJAAAA	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.3.5_1.10.2.jar) 
	UCHIJAAAA	props{2.3.4} [Decocraft] (Decocraft-2.3.5_1.10.2.jar) 
	UCHIJAAAA	forestry{5.2.16.328} [Forestry] (forestry_1.10.2-5.2.16.328.jar) 
	UCHIJAAAA	eleccore{1.6.379} [ElecCore] (ElecCore-1.10.2-1.6.379.jar) 
	UCHIJAAAA	OpenComputers{1.6.0.4} [OpenComputers] (OpenComputers-MC1.10.2-1.6.0.4.jar) 
	UCHIJAAAA	deepresonance{1.4.2} [DeepResonance] (deepresonance-1.1x-1.4.2.jar) 
	UCHIJAAAA	economylite{2.6.2} [EconomyLite] (EconomyLite-5.0.0-2.6.2.jar) 
	UCHIJAAAA	elevatorid{1.2.0} [Elevator Mod] (ElevatorMod[V.1.2.0][MC.1.10.2].jar) 
	UCHIJAAAA	endercore{1.10.2-0.4.1.60-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.60-beta.jar) 
	UCHIJAAAA	EnderIO{1.10.2-3.0.1.137_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.137_beta.jar) 
	UCHIJAAAA	shetiphiancore{3.3.5} [ShetiPhian-Core] (shetiphiancore-1.10.0-3.3.5.jar) 
	UCHIJAAAA	endertanks{1.4.7} [EnderTanks] (endertanks-1.10.0-1.4.7.jar) 
	UCHIJAAAA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-1.1.3d.jar) 
	UCHIJAAAA	zerocore{1.10.2-0.0.8.1} [Zero CORE] (zerocore-1.10.2-0.0.8.1.jar) 
	UCHIJAAAA	bigreactors{0.4.5.19} [Extreme Reactors] (ExtremeReactors-1.10.2-0.4.5.19.jar) 
	UCHIJAAAA	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UCHIJAAAA	ftbl{0.0.0} [FTBLib] (FTBLib-1.10.2-3.1.5.jar) 
	UCHIJAAAA	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.10.2-3.1.4.jar) 
	UCHIJAAAA	gendustry{1.6.4.24} [GenDustry] (gendustry-1.6.4.24-mc1.10.2.jar) 
	UCHIJAAAA	geographicraft{0.8.5} [GeographiCraft] (GeographiCraft-0.8.5.jar) 
	UCHIJAAAA	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.2-45.jar) 
	UCHIJAAAA	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.3.0} [JourneyMap] (journeymap-1.10.2-5.3.0.jar) 
	UCHIJAAAA	k4lib{1.10.2-1.0.66} [K4Lib] (k4lib-1.10.2-1.0.66-universal.jar) 
	UCHIJAAAA	kleeslabs{3.3.5} [KleeSlabs] (KleeSlabs_1.10.2-3.3.5.jar) 
	UCHIJAAAA	malisiscore{1.10.2-4.2.7} [MalisisCore] (malisiscore-1.10.2-4.2.7.jar) 
	UCHIJAAAA	malisisdoors{1.10.2-5.1.4} [MalisisDoors] (malisisdoors-1.10.2-5.1.4.jar) 
	UCHIJAAAA	missing_pieces{4.1.0} [Missing Pieces] (missing_pieces-1.10.2-4.1.0.jar) 
	UCHIJAAAA	testdummy{1.11} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.11.jar) 
	UCHIJAAAA	mtlib{@VERSION@} [MTLib] (MTLib-1.0.0.jar) 
	UCHIJAAAA	multistorage{1.2.9} [Multi-Storage] (multistorage-1.10.0-1.2.9.jar) 
	UCHIJAAAA	NotEnoughCodecs{0.5} [NotEnoughCodecs] (NotEnoughCodecs-0.5.jar) 
	UCHIJAAAA	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	UCHIJAAAA	permissionsex{2.0-SNAPSHOT-oretesting} [PermissionsEx] (permissionsex-sponge-2.0-SNAPSHOT-shaded.jar) 
	UCHIJAAAA	platforms{1.2.4} [Platforms] (platforms-1.10.0-1.2.4.jar) 
	UCHIJAAAA	pjw{0.11.4} [ProjectWorlds] (projectworlds-5.1.0-0.11.4.jar) 
	UCHIJAAAA	PvpToggle{1.10-1.0.36} [PVP Toggle] (pvpToggle-1.10-1.0.36-universal.jar) 
	UCHIJAAAA	railcraft{10.0.0} [Railcraft] (Railcraft_1.10.2-10.0.0.jar) 
	UCHIJAAAA	redstonepaste{1.7.4} [Redstone Paste] (redstonepaste-mc1.9.4-1.7.4.jar) 
	UCHIJAAAA	rftools{5.76} [RFTools] (rftools-1.1x-5.76.jar) 
	UCHIJAAAA	rftoolscontrol{1.6.3} [RFTools Control] (rftoolsctrl-1.1x-1.6.3.jar) 
	UCHIJAAAA	RTG{4.1.2.1} [Realistic Terrain Generation] (RTG-1.10.2-4.1.2.1.jar) 
	UCHIJAAAA	Signals{1.0} [Signals] (Signals-1.10.2-0.5.0-universal.jar) 
	UCHIJAAAA	signpic{2.5.1} [SignPicture] (SignPicture-1.10.2-2.5.1-universal.jar) 
	UCHIJAAAA	simplebarrels{1.25h} [Simple Barrels] (simplebarrels-1.10.2-2002-1.25h.jar) 
	UCHIJAAAA	valkyrielib{1.10.2-0.10.5d} [Valkyrie Lib] (valkyrielib-1.10.2-0.10.5e.jar) 
	UCHIJAAAA	simplegenerators{1.10.2-0.10.5b} [Simple Generators] (simplegenerators-1.10.2-0.10.5b.jar) 
	UCHIJAAAA	simpleretrogen{4.0.1+8} [Simple Retrogen] (simpleretrogen-1.10-4.0.1+8.jar) 
	UCHIJAAAA	spongeboard{} [spongeboard] (SpongeBoard-2.4-SNAPSHOT-all.jar) 
	UCHIJAAAA	StorageDrawers{1.10.2-3.5.1} [Storage Drawers] (StorageDrawers-1.10.2-3.5.1.jar) 
	UCHIJAAAA	rscircuits{1.0.4} [Super Circuit Maker] (SuperCircuitMaker-1.0.4.jar) 
	UCHIJAAAA	supercraftingframe{1.2.1.88} [Super Crafting Frame] (supercraftingframe-1.10.2-1.2.1.88.jar) 
	UCHIJAAAA	theoneprobe{1.3.3} [The One Probe] (theoneprobe-1.10-1.3.3.jar) 
	UCHIJAAAA	usefulnullifiers{1.2.1} [Useful Nullifiers] (usefulnullifiers-1.2.1.jar) 
	UCHIJAAAA	gvc{0.6.1} [§aGlibys§f Voice Chat Mod] (VoiceChat-1.9-0.6.1.jar) 
	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.10.2-4.2.7.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.3.jar)
  team.chisel.common.asm.ChiselTransformer
CoreMod (Aroma1997Core-1.9.4-1.1.1.1.jar)
  
LoadingPlugin (Quark-r1.1-70.jar)
  vazkii.quark.base.asm.ClassTransformer
NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.60-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.4.3.165-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.BlockStateLoaderTransformer
TransformerLoader (OpenComputers-MC1.10.2-1.6.0.4.jar)
  li.cil.oc.common.asm.ClassTransformer
BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.5.jar)
  shetiphian.core.asm.ClassTransformer
SpongeCoremod (spongeforge-1.10.2-2202-5.1.0-BETA-5.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
	List of loaded APIs: 
		* actuallyadditionsapi (29) from ActuallyAdditions-1.10.2-r97.jar
		* CharsetAPI (0.1) from Charset-mc1.10.2-0.3.4-9bf078fd9a3d0d9a.jar
		* CharsetAPI|Audio (0.0) from Charset-mc1.10.2-0.3.4-9bf078fd9a3d0d9a.jar
		* CharsetAPI|Lib (0.2) from Charset-mc1.10.2-0.3.4-9bf078fd9a3d0d9a.jar
		* CharsetAPI|Pipes (0.3) from Charset-mc1.10.2-0.3.4-9bf078fd9a3d0d9a.jar
		* CharsetAPI|Storage (0.1) from Charset-mc1.10.2-0.3.4-9bf078fd9a3d0d9a.jar
		* CharsetAPI|Tape (0.0) from Charset-mc1.10.2-0.3.4-9bf078fd9a3d0d9a.jar
		* CharsetAPI|Wires (0.3) from Charset-mc1.10.2-0.3.4-9bf078fd9a3d0d9a.jar
		* ChiselAPI (0.0.1) from Chisel-MC1.10.2-0.0.7.3.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.10.2-0.0.7.3.jar
		* ChiselsAndBitsAPI (12.5.0) from chiselsandbits-12.7.jar
		* CoFHAPI (1.8.9R1.2.0B1) from valkyrielib-1.10.2-0.10.5e.jar
		* CoFHAPI|block (1.8.9R1.2.0B1) from zerocore-1.10.2-0.0.8.1.jar
		* CoFHAPI|core (1.8.9R1.2.0B1) from zerocore-1.10.2-0.0.8.1.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from ActuallyAdditions-1.10.2-r97.jar
		* CoFHAPI|inventory (1.8.9R1.2.0B1) from valkyrielib-1.10.2-0.10.5e.jar
		* CoFHAPI|item (1.8.9R1.2.0B1) from mcjtylib-1.1x-2.3.1.jar
		* CoFHAPI|tileentity (1.8.9R1.2.0B1) from zerocore-1.10.2-0.0.8.1.jar
		* CoFHAPI|transport (1.8.9R1.2.0B1) from zerocore-1.10.2-0.0.8.1.jar
		* compatlayer (0.1.7) from compatlayer-1.10-0.1.7.jar
		* ComputerCraft|API (1.80pr0) from zerocore-1.10.2-0.0.8.1.jar
		* ComputerCraft|API|FileSystem (1.80pr0) from zerocore-1.10.2-0.0.8.1.jar
		* ComputerCraft|API|Lua (1.80pr0) from zerocore-1.10.2-0.0.8.1.jar
		* ComputerCraft|API|Media (1.80pr0) from zerocore-1.10.2-0.0.8.1.jar
		* ComputerCraft|API|Peripheral (1.80pr0) from zerocore-1.10.2-0.0.8.1.jar
		* ComputerCraft|API|Permissions (1.80pr0) from zerocore-1.10.2-0.0.8.1.jar
		* ComputerCraft|API|Redstone (1.80pr0) from zerocore-1.10.2-0.0.8.1.jar
		* ComputerCraft|API|Turtle (1.80pr0) from zerocore-1.10.2-0.0.8.1.jar
		* CSLib|API (0.3.0) from Decocraft-2.3.5_1.10.2.jar
		* DR-API (1.0.4-Beta) from deepresonance-1.1x-1.4.2.jar
		* ElecCoreAPI (1.0) from ElecCore-1.10.2-1.6.379.jar
		* ElecCore|Abilities (#API_VER#) from ElecCore-1.10.2-1.6.379.jar
		* EnderIOAPI (0.0.2) from EnderIO-1.10.2-3.0.1.137_beta.jar
		* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.10.2-3.0.1.137_beta.jar
		* EnderIOAPI|Teleport (0.0.2) from EnderIO-1.10.2-3.0.1.137_beta.jar
		* EnderIOAPI|Tools (0.0.2) from EnderIO-1.10.2-3.0.1.137_beta.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.10.2-5.2.16.328.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.10.2-5.2.16.328.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.10.2-5.2.16.328.jar
		* ForestryAPI|climate (2.1.0) from forestry_1.10.2-5.2.16.328.jar
		* ForestryAPI|core (5.1.0) from forestry_1.10.2-5.2.16.328.jar
		* ForestryAPI|farming (2.1.0) from forestry_1.10.2-5.2.16.328.jar
		* ForestryAPI|food (1.1.0) from forestry_1.10.2-5.2.16.328.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.10.2-5.2.16.328.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.10.2-5.2.16.328.jar
		* ForestryAPI|greenhouse (5.2.0) from forestry_1.10.2-5.2.16.328.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.10.2-5.2.16.328.jar
		* ForestryAPI|lepidopterology (1.3.0) from forestry_1.10.2-5.2.16.328.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.10.2-5.2.16.328.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.10.2-5.2.16.328.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.10.2-5.2.16.328.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.10.2-5.2.16.328.jar
		* ForestryAPI|world (2.1.0) from forestry_1.10.2-5.2.16.328.jar
		* gendustryAPI (2.3.0) from gendustry-1.6.4.24-mc1.10.2.jar
		* Guide-API|API (1.10.2-2.0.2-45) from Guide-API-1.10.2-2.0.2-45.jar
		* journeymap|client-api (1.3) from journeymap-1.10.2-5.3.0.jar
		* journeymap|client-api-display (1.3) from journeymap-1.10.2-5.3.0.jar
		* journeymap|client-api-event (1.3) from journeymap-1.10.2-5.3.0.jar
		* journeymap|client-api-model (1.3) from journeymap-1.10.2-5.3.0.jar
		* journeymap|client-api-util (1.3) from journeymap-1.10.2-5.3.0.jar
		* JustEnoughItemsAPI (4.10.1) from jei_1.10.2-3.13.5.385.jar
		* mcjtylib_ng (2.3.1) from mcjtylib-1.1x-2.3.1.jar
		* OpenComputersAPI|Component (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.0.4.jar
		* OpenComputersAPI|Core (6.0.0-alpha) from zerocore-1.10.2-0.0.8.1.jar
		* OpenComputersAPI|Driver (6.0.0-alpha) from zerocore-1.10.2-0.0.8.1.jar
		* OpenComputersAPI|Driver|Item (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.0.4.jar
		* OpenComputersAPI|Event (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.0.4.jar
		* OpenComputersAPI|FileSystem (6.0.0-alpha) from zerocore-1.10.2-0.0.8.1.jar
		* OpenComputersAPI|Internal (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.0.4.jar
		* OpenComputersAPI|Machine (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.0.4.jar
		* OpenComputersAPI|Manual (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.0.4.jar
		* OpenComputersAPI|Network (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.0.4.jar
		* OpenComputersAPI|Prefab (6.0.0-alpha) from zerocore-1.10.2-0.0.8.1.jar
		* railcraft:API|core (2.0.0) from Railcraft_1.10.2-10.0.0.jar
		* RailcraftAPI|bore (2.0.0) from Railcraft_1.10.2-10.0.0.jar
		* RailcraftAPI|carts (2.0.0) from Railcraft_1.10.2-10.0.0.jar
		* RailcraftAPI|charge (3.0.0) from Railcraft_1.10.2-10.0.0.jar
		* RailcraftAPI|crafting (2.0.0) from Railcraft_1.10.2-10.0.0.jar
		* RailcraftAPI|events (2.0.0) from Railcraft_1.10.2-10.0.0.jar
		* RailcraftAPI|fuel (2.0.0) from Railcraft_1.10.2-10.0.0.jar
		* RailcraftAPI|helpers (2.0.0) from Railcraft_1.10.2-10.0.0.jar
		* RailcraftAPI|items (2.0.0) from Railcraft_1.10.2-10.0.0.jar
		* RailcraftAPI|locomotive (2.0.0) from Railcraft_1.10.2-10.0.0.jar
		* RailcraftAPI|signals (3.0.0) from Railcraft_1.10.2-10.0.0.jar
		* RailcraftAPI|tracks (3.0.0) from Railcraft_1.10.2-10.0.0.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.5.1.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.5.1.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.5.1.jar
		* StorageDrawersAPI|inventory (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.5.1.jar
		* StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.5.1.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.5.1.jar
		* StorageDrawersAPI|render (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.5.1.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.5.1.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.5.1.jar
		* valkyrielib.api (1.10.2-0.10.5d) from valkyrielib-1.10.2-0.10.5e.jar
		* zerocore|API|multiblock (1.9.4-0.0.1) from zerocore-1.10.2-0.0.8.1.jar
		* zerocore|API|multiblock|rectangular (1.9.4-0.0.1) from zerocore-1.10.2-0.0.8.1.jar
		* zerocore|API|multiblock|validation (1.9.4-0.0.1) from zerocore-1.10.2-0.0.8.1.jar
	EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                 An unsupported base software is installed: 'sponge'. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/home/industrial/mcmyadmin/Minecraft/mods/mcjtylib-1.1x-2.3.1.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/home/industrial/mcmyadmin/Minecraft/mods/mcjtylib-1.1x-2.3.1.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/home/industrial/mcmyadmin/Minecraft/mods/mcjtylib-1.1x-2.3.1.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/home/industrial/mcmyadmin/Minecraft/mods/mcjtylib-1.1x-2.3.1.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/home/industrial/mcmyadmin/Minecraft/mods/mcjtylib-1.1x-2.3.1.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/home/industrial/mcmyadmin/Minecraft/mods/mcjtylib-1.1x-2.3.1.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/home/industrial/mcmyadmin/Minecraft/mods/mcjtylib-1.1x-2.3.1.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/home/industrial/mcmyadmin/Minecraft/mods/mcjtylib-1.1x-2.3.1.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/home/industrial/mcmyadmin/Minecraft/mods/mcjtylib-1.1x-2.3.1.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

	Profiler Position: N/A (disabled)
	Player Count: 0 / 100; []
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by McJty** [comment]
I will check it out soon

**Comment by McJty** [comment]
@Elec332 any idea how this can happen?

**Comment by McJty** [comment]
Fixed it for now. The underlying issue is probably still there though
