### ISSUE TITLE
DRTank and (Maybe) TEMagmaCrucible Crash.

### ISSUE THREAD

**Issue by FairleyC** [McJty/DeepResonance#207]
Today we updated to FTBBeyond (1.6.1) and had a local crash around someones base.

Log:
`Head --
Thread: Server thread
Stacktrace:
at java.util.Objects.requireNonNull(Objects.java:203)
at java.util.Optional.<init>(Optional.java:96)
at java.util.Optional.of(Optional.java:108)
at mcjty.deepresonance.blocks.tank.TileTank.onTileUnloaded(TileTank.java:170)
at mcjty.deepresonance.blocks.tank.TileTank.func_145843_s(TileTank.java:151)
at net.minecraft.world.chunk.Chunk.func_177426_a(Chunk.java:816)
at net.minecraft.world.World.func_72939_s(World.java:1872)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)`

`deepresonance{1.4.7} [DeepResonance] (deepresonance-1.1x-1.4.7.jar)`

`thermalexpansion{5.0.4} [Thermal Expansion] (ThermalExpansion-1.10.2-5.0.4.90-universal.jar)`

After chasing down tanks within the area we found this setup: [imgur](http://i.imgur.com/2t6msOE.png)

The stone replaced tanks.

**Comment by McJty** [comment]
This bug has been reported more then 10 times already and has been fixed several weeks ago in 1.4.8
