### ISSUE TITLE
[1.12] Issue when turning on laser

### ISSUE THREAD

**Issue by winsrp** [McJty/DeepResonance#218]
Creative test world, making a test setup to see if everything works.

using 64 quartz and a single creative crystal on the laser, (there was no liquid in the lens attached tank.)

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.2-101.jar)
  MovingWorldCoreMod (movingworld-1.12-4.340-full.jar)
  MalisisCorePlugin (malisiscore-1.12-6.0.1.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 7/18/17 3:25 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at mcjty.deepresonance.blocks.laser.LaserTileEntity.infuseLiquid(LaserTileEntity.java:162)
	at mcjty.deepresonance.blocks.laser.LaserTileEntity.checkStateServer(LaserTileEntity.java:141)
	at mcjty.deepresonance.blocks.laser.LaserTileEntity.func_73660_a(LaserTileEntity.java:91)
	at net.minecraft.world.World.func_72939_s(World.java:1807)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:761)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at mcjty.deepresonance.blocks.laser.LaserTileEntity.infuseLiquid(LaserTileEntity.java:162)
	at mcjty.deepresonance.blocks.laser.LaserTileEntity.checkStateServer(LaserTileEntity.java:141)
	at mcjty.deepresonance.blocks.laser.LaserTileEntity.func_73660_a(LaserTileEntity.java:91)

-- Block entity being ticked --
Details:
	Name: minecraft:deepresonance_laser // mcjty.deepresonance.blocks.laser.LaserTileEntity
	Block type: ID #1051 (tile.deepresonance.laser // mcjty.deepresonance.blocks.laser.LaserBlock)
	Block data value: 5 / 0x5 / 0b0101
	Block location: World: (-1913,6,-877), Chunk: (at 7,0,3 in -120,-55; contains blocks -1920,0,-880 to -1905,255,-865), Region: (-4,-2; contains chunks -128,-64 to -97,-33, blocks -2048,0,-1024 to -1537,255,-513)
	Actual block type: ID #1051 (tile.deepresonance.laser // mcjty.deepresonance.blocks.laser.LaserBlock)
	Actual block data value: 5 / 0x5 / 0b0101
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1807)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['winsrp'/107, l='New World', x=-1910.90, y=4.00, z=-875.61]]
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: -2637941171755461266
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-1941,4,-870), Chunk: (at 11,0,10 in -122,-55; contains blocks -1952,0,-880 to -1937,255,-865), Region: (-4,-2; contains chunks -128,-64 to -97,-33, blocks -2048,0,-1024 to -1537,255,-513)
	Level time: 30664 game time, 5467 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 54686 (now: false), thunder time: 2114 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:761)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by McJty** [comment]
Probably also related to the faulty tank issue.
For @Elec332
