### ISSUE TITLE
Invalid registration attempt

### ISSUE THREAD

**Issue by TekuSP** [McJty/DeepResonance#220]
```
[22:11:22] [Server thread/WARN] [FML]: ****************************************
[22:11:22] [Server thread/WARN] [FML]: * Invalid registration attempt for an Ore Dictionary item with name oreResonating has occurred. The registration has been denied to prevent crashes. The mod responsible for the registration needs to correct this.
[22:11:22] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:619)
[22:11:22] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:605)
[22:11:22] [Server thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:604)
[22:11:22] [Server thread/WARN] [FML]: *  at mcjty.deepresonance.ForgeEventHandlers.registerBlocks(ForgeEventHandlers.java:37)
[22:11:22] [Server thread/WARN] [FML]: *  at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_180_ForgeEventHandlers_registerBlocks_Register.invoke(.dynamic)
[22:11:22] [Server thread/WARN] [FML]: *  at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)...
[22:11:22] [Server thread/WARN] [FML]: ****************************************
```
No crash, I suppose its this mod fault because of call stack.

Deep Resonance 1.12-1.4.9
MjctLib 1.12-2.4.4
```
[21:50:07] [main/INFO] [FML]: Forge Mod Loader version 14.21.1.2420 for Minecraft 1.12 loading
[21:50:07] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_141, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_141
```

**Comment by bookerthegeek** [comment]
### Heyo ###
Just dropping by to let you know this is still an issue with the latest version
#### Version ####
- Minecraft 1.12.2
- jre1.8.0_151
- forge-1.12.2-14.23.1.2575-universal.jar
- mcjtylib-1.12-2.5.0
- deepresonance-1.12-1.5.0
#### Log ####
```
[16:57:59] [main/WARN] [FML]: ****************************************
[16:57:59] [main/WARN] [FML]: * Invalid registration attempt for an Ore Dictionary item with name oreResonating has occurred. The registration has been denied to prevent crashes. The mod responsible for the registration needs to correct this.
[16:57:59] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:642)
[16:57:59] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:628)
[16:57:59] [main/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:627)
[16:57:59] [main/WARN] [FML]: *  at mcjty.deepresonance.ForgeEventHandlers.registerBlocks(ForgeEventHandlers.java:37)
[16:57:59] [main/WARN] [FML]: *  at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_872_ForgeEventHandlers_registerBlocks_Register.invoke(.dynamic)
[16:57:59] [main/WARN] [FML]: *  at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)...
[16:57:59] [main/WARN] [FML]: ****************************************
```

**Comment by McJty** [comment]
Hmm I actually don't know what's wrong here. This is my code:

        OreDictionary.registerOre("oreResonating", ModBlocks.resonatingOreBlock);

**Comment by McJty** [comment]
nm. Fixed it for next release

**Comment by bookerthegeek** [comment]
I don't know enough Java to be of assistance. But you've done some amazing work. I don't know if this breaks anything in game as your mods are the only ones I k ow of that use resonating ore, but I'll dig around and see if I can help figure it out.

**Comment by LemADEC** [comment]
The item needs to be created and registered before adding to the dictionary.

**Comment by McJty** [comment]
Hey guys. I fixed it already :-)
