### ISSUE TITLE
Server crash with ticking entity

### ISSUE THREAD

**Issue by utoc** [McJty/DeepResonance#91]
```
Stacktrace:
at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:196)
at mcjty.deepresonance.blocks.smelter.SmelterTileEntity.checkStateServer(SmelterTileEntity.java:83)
at mcjty.deepresonance.blocks.smelter.SmelterTileEntity.func_73660_a(SmelterTileEntity.java:67)
```

Running:
    FML 1.10.2-12.18.0.2008
    mcjtylib-1.10-1.9.8
    deepresonance-1.9.4-1.2.0beta35
on Minecraft 1.10.2

Crash report here: http://pastebin.com/BNru8Dis

This is a one-off crash that hasn't happened before.

**Comment by ProsperCraft** [comment]
Why did you close this? We just got this.

**Comment by Orcinuss** [comment]
We've been getting this for the better part of 3 days now. Crashes about once every 2 hours because of this.

**Comment by McJty** [comment]
Are you all using Sponge?

**Comment by Orcinuss** [comment]
I am and I know @ProsperCraft is.

**Comment by McJty** [comment]
I don't know what Sponge is doing but these kinds of crashes are really impossible normally. I'm getting reports on rftools too. I can add protection for this everywhere but that's really annoying, will slow things down and is actually not a real fix as the underlying code is still wrong. Sorry, but I'm losing all thrust in Sponge. It seems to be messing with things that it should not mess with.

**Comment by Orcinuss** [comment]
You could try messaging @bloodmc. I don't know how to pull him into this thread. Im sure he'd listen to you, being one of the major mod devs in 1.10+ now. Congrats on that btw.

**Comment by Orcinuss** [comment]
Could you add a check that detects the server brand and if its a sponge server, run specific code to hopefully prevent some of these crashes?

**Comment by McJty** [comment]
That would be even worse then simply doing the test to be honest. I *can* add the tests. They are as such no problem and make it safer in general. However, I'm very annoyed that Sponge seems to be triggering these kinds of 'illegal' situations. I mean look closely at the crash. What is happening is that my tile entity gets ticked but the block at the location of the tile entity is air. That does not happen normally.

**Comment by Orcinuss** [comment]
I know... Its stupid and your mods aren't the only ones being affected. Having a similar issue with Applied Energistics and Immersive Engineering too.

**Comment by McJty** [comment]
Ok, seems Sponge is aware of this issue and they are working on a fix

**Comment by McJty** [comment]
BTW, for everyone having this issue. Does this happen on blocks you are not touching in any way or only when placing/removing those blocks?

**Comment by Orcinuss** [comment]
It seems to be happening when pipes are trying to access the block. Mostly EnderIO conduits inserting and exporting liquids. I does not happen when directly placing or breaking the block. Only when it is being interacted with.

**Comment by bloodmc** [comment]
@Orcinuss @ProsperCraft @utoc Can you reproduce this reliably? If so please setup a test world and let me know the steps to take so I can fix the issue on Sponge's end.

**Comment by utoc** [comment]
@bloodmc This ticket was opened due to a bug that existed in stock Forge. Mcjty has corrected that bug and as such, I have not experienced it in months.

**Comment by Nodlehs** [comment]
We are getting this issue in the Beyond pack. 

[Relevant crash info](http://pastebin.com/6b4gFYdd) 

This seems to happen when the generator is on and you mess with the crystal (break/etc) It also happened when I broke a block near the generator (a non-deep resonance block)

``

**Comment by Elec332** [comment]
@Nodlehs Can you please provide the _full_ game log?

**Comment by Nodlehs** [comment]
Sure, I'll ask the server admin to send the full log to me
